--------------------------------------------------------
--  File created - Monday-August-24-2020   
--------------------------------------------------------
DROP SEQUENCE "SEQ_BOOKING_SER";
DROP SEQUENCE "SEQ_MANAGER_ID";
DROP TABLE "BOOKING";
DROP TABLE "CARD";
DROP TABLE "EMPWORKDATE";
DROP TABLE "HISTORYCARDDATA";
DROP TABLE "HOROSCOPE";
DROP TABLE "MANAGER";
DROP TABLE "MEMBER";
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOKING_SER
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOOKING_SER"  MINVALUE 1 MAXVALUE 5000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MANAGER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MANAGER_ID"  MINVALUE 1 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "TEA10103"."MANAGER" 
   (	"SERIAL" NUMBER, 
	"ACCOUNT" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"PICTURE" BLOB, 
	"AUTHORITY" NUMBER(1,0), 
	"INTRODUCTION" VARCHAR2(200 BYTE), 
	"MAINPULATE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE),
	"EMAIL" VARCHAR2(50 BYTE),
	CONSTRAINT FK_MANAGER_EMAIL
    FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PICTURE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEA10103"."MANAGER"."SERIAL" IS '序號';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."ACCOUNT" IS '帳號';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."NAME" IS '姓名';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."NICKNAME" IS '暱稱';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."PASSWORD" IS '密碼';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."PICTURE" IS '大頭照';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."AUTHORITY" IS '權限';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."INTRODUCTION" IS '自我介紹';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."MAINPULATE" IS '操作';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."DESCRIPTION" IS '身分說明';
   COMMENT ON COLUMN "TEA10103"."MANAGER"."EMAIL" IS '電子信箱';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "TEA10103"."MEMBER" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(10 BYTE), 
	"CITY" VARCHAR2(10 BYTE), 
	"AREA" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"BIRTHDAY" DATE, 
	"GENDER" VARCHAR2(1 BYTE), 
	"KNOW" VARCHAR2(100 BYTE), 
	"OCCUPATION" VARCHAR2(50 BYTE), 
	"EPAPER" NUMBER(1,0), 
	"NICKNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
     COMMENT ON COLUMN "TEA10103"."MEMBER"."EMAIL" IS '電子信箱';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."PASSWORD" IS '密碼';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."NAME" IS '姓名';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."PHONE" IS '行動電話';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."CITY" IS '縣市別';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."AREA" IS '郵遞區域';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."ADDRESS" IS '地址';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."BIRTHDAY" IS '生日';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."GENDER" IS '性別';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."KNOW" IS '如何得知本站';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."OCCUPATION" IS '職業';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."EPAPER" IS '是否訂閱電子報';
	 COMMENT ON COLUMN "TEA10103"."MEMBER"."NICKNAME" IS '暱稱';
	 
  
REM INSERTING into TEA10103.BOOKING
SET DEFINE OFF;
REM INSERTING into TEA10103.CARD
SET DEFINE OFF;
REM INSERTING into TEA10103.EMPWORKDATE
SET DEFINE OFF;
REM INSERTING into TEA10103.HISTORYCARDDATA
SET DEFINE OFF;
REM INSERTING into TEA10103.HOROSCOPE
SET DEFINE OFF;
REM INSERTING into TEA10103.MANAGER
SET DEFINE OFF;
REM INSERTING into TEA10103.MEMBER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "BOOKING" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"EMPID" NUMBER, 
	"BDATE" DATE, 
	"BTIMES" VARCHAR2(5 BYTE), 
	"SERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BOOKING"."USERID" IS '預約的使用者serid';
   COMMENT ON COLUMN "BOOKING"."EMPID" IS '被預約的員工id';
   COMMENT ON COLUMN "BOOKING"."BDATE" IS '預約日期';
   COMMENT ON COLUMN "BOOKING"."BTIMES" IS '(Day/N上午/o下午/晚上)on/night';
   COMMENT ON COLUMN "BOOKING"."SERID" IS '預約單流水號';
   COMMENT ON TABLE "BOOKING"  IS 'BOOKING.SERID 用序號機SEQ_BOOKING_SER產生';
--------------------------------------------------------
--  DDL for Table CARD
--------------------------------------------------------

  CREATE TABLE "CARD" 
   (	"ID" NUMBER(20,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"OVERALL" VARCHAR2(400 BYTE), 
	"LOVE" VARCHAR2(400 BYTE), 
	"RICH" VARCHAR2(400 BYTE), 
	"HEALTH" VARCHAR2(400 BYTE), 
	"PICTURE" BLOB, 
	"KEYWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PICTURE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMPWORKDATE
--------------------------------------------------------

  CREATE TABLE "EMPWORKDATE" 
   (	"EMPID" NUMBER, 
	"WDATE" DATE, 
	"WTIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "EMPWORKDATE"."WDATE" IS '上班日期';
   COMMENT ON COLUMN "EMPWORKDATE"."WTIME" IS '上午/下午/晚上';
--------------------------------------------------------
--  DDL for Table HISTORYCARDDATA
--------------------------------------------------------

  CREATE TABLE "HISTORYCARDDATA" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"OVERALL" VARCHAR2(400 BYTE), 
	"LOVE" VARCHAR2(400 BYTE), 
	"RICH" VARCHAR2(400 BYTE), 
	"HEALTH" VARCHAR2(400 BYTE), 
	"PICTURE" BLOB, 
	"KEYWORD" VARCHAR2(40 BYTE), 
	"EAMIL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PICTURE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table HOROSCOPE
--------------------------------------------------------

  CREATE TABLE "HOROSCOPE" 
   (	"ID" NUMBER, 
	"COLUMN2" VARCHAR2(1000 BYTE), 
	"PICTURE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PICTURE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------
--  DDL for Index HOROSCOPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOROSCOPE_PK" ON "HOROSCOPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARD_PK" ON "CARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER_PK" ON "MANAGER" ("SERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORYCARDDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORYCARDDATA_PK" ON "HISTORYCARDDATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOKING_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKING_PK1" ON "BOOKING" ("SERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger BOOKING_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOOKING_TRG" 
BEFORE INSERT ON BOOKING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT SEQ_BOOKING_SER.NEXTVAL INTO :NEW.SERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKING_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORYCARDDATA
--------------------------------------------------------

  ALTER TABLE "HISTORYCARDDATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HISTORYCARDDATA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HISTORYCARDDATA" ADD CONSTRAINT "HISTORYCARDDATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "MANAGER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MANAGER" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "MANAGER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("SERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MANAGER" MODIFY ("SERIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("EPAPER" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARD
--------------------------------------------------------

  ALTER TABLE "CARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CARD" ADD CONSTRAINT "CARD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOROSCOPE
--------------------------------------------------------

  ALTER TABLE "HOROSCOPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HOROSCOPE" ADD CONSTRAINT "HOROSCOPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "BOOKING" MODIFY ("BTIMES" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BDATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("EMPID" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_PK" PRIMARY KEY ("SERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOOKING" MODIFY ("SERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPWORKDATE
--------------------------------------------------------

  ALTER TABLE "EMPWORKDATE" MODIFY ("WTIME" NOT NULL ENABLE);
  ALTER TABLE "EMPWORKDATE" MODIFY ("WDATE" NOT NULL ENABLE);
  ALTER TABLE "EMPWORKDATE" MODIFY ("EMPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_FK1" FOREIGN KEY ("EMPID")
	  REFERENCES "MANAGER" ("SERIAL") ENABLE;
  ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPWORKDATE
--------------------------------------------------------

  ALTER TABLE "EMPWORKDATE" ADD CONSTRAINT "EMPWORKDATE_FK1" FOREIGN KEY ("EMPID")
	  REFERENCES "MANAGER" ("SERIAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORYCARDDATA
--------------------------------------------------------

  ALTER TABLE "HISTORYCARDDATA" ADD CONSTRAINT "HISTORYCARDDATA_FK1" FOREIGN KEY ("EAMIL")
	  REFERENCES "MEMBER" ("EMAIL") ENABLE;
